export const COUNTRIES_LOAD_REQUEST = "COUNTRIES_LOAD_REQUEST";
export const COUNTRIES_LOAD_SUCCESS = "COUNTRIES_LOAD_SUCCESS";
export const COUNTRIES_LOAD_FAIL = "COUNTRIES_LOAD_FAIL";

export const COUNTRIES_SEARCH_REQUEST = "COUNTRIES_SEARCH_REQUEST";
export const COUNTRIES_SEARCH_SUCCESS = "COUNTRIES_SEARCH_SUCCESS";
export const COUNTRIES_SEARCH_FAIL = "COUNTRIES_SEARCH_FAIL";

export const COUNTRIES_FILTER_REGION = "COUNTRIES_FILTER_REGION";

export const DETAIL_LOAD_REQUEST = "DETAIL_LOAD_REQUEST";
export const DETAIL_LOAD_SUCCESS = "DETAIL_LOAD_SUCCESS";
export const DETAIL_LOAD_FAIL = "DETAIL_LOAD_FAIL";