export const COUNTRIES_LOAD_REQUEST = "COUNTRIES_LOAD_REQUEST";
export const COUNTRIES_LOAD_SUCCESS = "COUNTRIES_LOAD_SUCCESS";
export const COUNTRIES_LOAD_FAIL = "COUNTRIES_LOAD_FAIL";

export const COUNTRIES_INPUT_CHANGE = "COUNTRIES_INPUT_CHANGE";
export const COUNTRIES_SEARCH = "COUNTRIES_SEARCH";
export const COUNTRIES_FILTER_REGION = "COUNTRIES_FILTER_REGION";

export const DETAIL_LOAD_REQUEST = "DETAIL_LOAD_REQUEST";
export const DETAIL_LOAD_SUCCESS = "DETAIL_LOAD_SUCCESS";
export const DETAIL_LOAD_FAIL = "DETAIL_LOAD_FAIL";